# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Testing

on:
  workflow_call:
  workflow_dispatch:

env:
  default-python: '3.11'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        tox_env: [py39, py310, py311, py312, py313]
        include:
          - tox_env: style
          - tox_env: docstyle
          - tox_env: check-manifest
          - tox_env: check-testdir
          - tox_env: check-headers
          - tox_env: check-apidocsdir
          - tox_env: mkdocs
            pandoc: true
            os: ubuntu-22.04

    # The operative sistem
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    # the steps of the CI
    steps:
      - uses: actions/checkout@master

      # optionals
      - name: Install pandoc
        if: ${{ matrix.pandoc }}
        run: sudo apt-get install pandoc

      - name: Determine Python version
        id: pyversion
        if: ${{ startsWith( matrix.tox_env, 'py3' ) }}
        uses: bluwy/substitute-string-action@v1
        with:
          _input-text: ${{ matrix.tox_env }}
          py3: "3."

      # tox steps
      - name: Set up Python ${{ steps.pyversion.outputs.result || env.default-python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.pyversion.outputs.result || env.default-python }}

      - name: Install tox
        run: pip install tox

      - name: tox -re ${{ matrix.tox_env }}
        run: tox -re ${{ matrix.tox_env }}

      # post optionals
      - name: Coverage
        if: ${{ startsWith( matrix.tox_env, 'py3' ) }}
        run: tox -e coverage
